create table if not exists public.resumes (
    id bigint generated by default as identity primary key,
    name text not null,
    project_input text not null,
    job_description text not null,
    resume_markdown text not null,
    created_at timestamptz not null default timezone('utc'::text, now())
);

alter table public.resumes enable row level security;

create policy "Public can read resumes"
on public.resumes
for select
to anon, authenticated
using (true);

create policy "Public can insert resumes"
on public.resumes
for insert
to anon, authenticated
with check (true);

create policy "Public can update resumes"
on public.resumes
for update
to anon, authenticated
using (true)
with check (true);

create policy "Public can delete resumes"
on public.resumes
for delete
to anon, authenticated
using (true);
