create table if not exists public.resumes (
    id bigint generated by default as identity primary key,
    user_id uuid,
    name text not null,
    project_input text not null,
    job_description text not null,
    resume_markdown text not null,
    created_at timestamptz not null default timezone('utc'::text, now())
);

alter table public.resumes
add column if not exists user_id uuid;

do $$
begin
    if not exists (
        select 1
        from pg_constraint
        where conname = 'resumes_user_id_fkey'
    ) then
        alter table public.resumes
        add constraint resumes_user_id_fkey
        foreign key (user_id) references auth.users(id) on delete cascade;
    end if;
end $$;

delete from public.resumes
where user_id is null;

alter table public.resumes
alter column user_id set not null;

alter table public.resumes enable row level security;

drop policy if exists "Public can read resumes" on public.resumes;
drop policy if exists "Public can insert resumes" on public.resumes;
drop policy if exists "Public can update resumes" on public.resumes;
drop policy if exists "Public can delete resumes" on public.resumes;
drop policy if exists "Users can read their own resumes" on public.resumes;
drop policy if exists "Users can insert their own resumes" on public.resumes;
drop policy if exists "Users can update their own resumes" on public.resumes;
drop policy if exists "Users can delete their own resumes" on public.resumes;

create policy "Users can read their own resumes"
on public.resumes
for select
to authenticated
using (auth.uid() = user_id);

create policy "Users can insert their own resumes"
on public.resumes
for insert
to authenticated
with check (auth.uid() = user_id);

create policy "Users can update their own resumes"
on public.resumes
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "Users can delete their own resumes"
on public.resumes
for delete
to authenticated
using (auth.uid() = user_id);
